### ISSUE TITLE
p_prior

### ISSUE THREAD

**Issue by crixus5678** [jacobeisenstein/DPMM#2]
In the code, p_prior is written as p_prior = params(it).counts + params(it).alpha * (params(it).counts == 0);
which lets the number of observations in k cluster be the probability of joining k cluster. 

But i thought, it should be divided by (a+N-1) ? which will gives

p_prior = (params(it).counts + params(it).alpha * (params(it).counts == 0))./(params(it).alpha+sum(params(it).counts)-1);

Or is the division redundant?

**Comment by jacobeisenstein** [comment]
the denominator (a+N-1) is constant, so it's not necessary as long as we
normalize the sampling distribution later

**Comment by crixus5678** [comment]
oh. thanks for the clarification
